from django.conf.urls import url
from . import views
from .views import (login_view,
                    register_view,
                    logout_view,
                    logout_within_account_view,
                    send_flat_view,
                    send_house_view,
                    send_parking_view,
                    send_land_view,
                    send_commercial_view,
                    send_industry_view,
                    send_auto_view,
                    send_equipment_view,
                    delete_flat_order_view,
                    delete_house_order_view,
                    delete_parking_order_view,
                    delete_land_order_view,
                    delete_commercial_order_view,
                    delete_industry_order_view,
                    delete_auto_order_view,
                    delete_equipment_order_view)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^house$', views.house, name='house'),
    url(r'^parking$', views.parking, name='parking'),
    url(r'^land$', views.land, name='land'),
    url(r'^commercial$', views.commercial, name='commercial'),
    url(r'^industry$', views.industry, name='industry'),
    url(r'^auto$', views.auto, name='auto'),
    url(r'^equipment$', views.equipment, name='equipment'),
    url(r'^detail_flat/(?P<flat_id>[0-9]+)/$', views.detail_flat, name='detail_flat'),
    url(r'^detail_house/(?P<house_id>[0-9]+)/$', views.detail_house, name='detail_house'),
    url(r'^detail_parking/(?P<parking_id>[0-9]+)/$', views.detail_parking, name='detail_parking'),
    url(r'^detail_land/(?P<land_id>[0-9]+)/$', views.detail_land, name='detail_land'),
    url(r'^detail_commercial/(?P<commercial_id>[0-9]+)/$', views.detail_commercial, name='detail_commercial'),
    url(r'^detail_industry/(?P<industry_id>[0-9]+)/$', views.detail_industry, name='detail_industry'),
    url(r'^detail_auto/(?P<auto_id>[0-9]+)/$', views.detail_auto, name='detail_auto'),
    url(r'^detail_equipment/(?P<equipment_id>[0-9]+)/$', views.detail_equipment, name='detail_equipment'),
    url(r'^delete_flat_order/(?P<flatorder_id>[0-9]+)/$', delete_flat_order_view, name='delete_flat_order'),
    url(r'^delete_house_order/(?P<houseorder_id>[0-9]+)/$', delete_house_order_view, name='delete_house_order'),
    url(r'^delete_parking_order/(?P<parkingorder_id>[0-9]+)/$', delete_parking_order_view, name='delete_parking_order'),
    url(r'^delete_land_order/(?P<landorder_id>[0-9]+)/$', delete_land_order_view, name='delete_land_order'),
    url(r'^delete_commercial_order/(?P<commercialorder_id>[0-9]+)/$', delete_commercial_order_view, name='delete_commercial_order'),
    url(r'^delete_industry_order/(?P<industryorder_id>[0-9]+)/$', delete_industry_order_view, name='delete_industry_order'),
    url(r'^delete_auto_order/(?P<autoorder_id>[0-9]+)/$', delete_auto_order_view, name='delete_auto_order'),
    url(r'^delete_equipment_order/(?P<equipmentorder_id>[0-9]+)/$', delete_equipment_order_view, name='delete_equipment_order'),
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^logout_within_account/$', logout_within_account_view, name='logout_within_account'),
    url(r'^account/$', views.account, name='account'),
    url(r'^send_flat/$', send_flat_view, name='send_flat'),
    url(r'^send_house/$', send_house_view, name='send_house'),
    url(r'^send_parking/$', send_parking_view, name='send_parking'),
    url(r'^send_land/$', send_land_view, name='send_land'),
    url(r'^send_commercial/$', send_commercial_view, name='send_commercial'),
    url(r'^send_industry/$', send_industry_view, name='send_industry'),
    url(r'^send_auto/$', send_auto_view, name='send_auto'),
    url(r'^send_equipment/$', send_equipment_view, name='send_equipment'),
]