# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('district', models.CharField(max_length=200, verbose_name='\u0420\u0430\u0439\u043e\u043d')),
                ('roomNumber', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442')),
                ('price', models.BigIntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('constYear', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u043f\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')),
                ('storey', models.IntegerField(verbose_name='\u042d\u0442\u0430\u0436')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('livingArea', models.FloatField(blank=True, null=True, verbose_name='\u0416\u0438\u043b\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('storeyNumber', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442')),
                ('constType', models.CharField(max_length=200, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u044f')),
                ('contacts', models.TextField(verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
                ('contactFace', models.CharField(max_length=200, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('address', models.CharField(max_length=400, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name_plural': '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b',
            },
        ),
    ]
