# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 1'),
        ),
    ]
