# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0006_auto_20161030_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='roomNumber',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '5+')], verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442'),
        ),
    ]
