# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0007_auto_20161030_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='constType',
            field=models.CharField(choices=[('\u041f\u0430\u043d\u0435\u043b\u044c\u043d\u044b\u0439', '\u041f\u0430\u043d\u0435\u043b\u044c\u043d\u044b\u0439'), ('\u041a\u0438\u0440\u043f\u0438\u0447\u043d\u044b\u0439', '\u041a\u0438\u0440\u043f\u0438\u0447\u043d\u044b\u0439'), ('\u041c\u043e\u043d\u043e\u043b\u0438\u0442\u043d\u044b\u0439', '\u041c\u043e\u043d\u043e\u043b\u0438\u0442\u043d\u044b\u0439')], max_length=200, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u044f'),
        ),
    ]
