# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0008_auto_20161030_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 2'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 3'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 4'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 5'),
        ),
    ]
