# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papp', '0013_land_landorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('\u0410\u043b\u043c\u0430\u0442\u044b', '\u0410\u043b\u043c\u0430\u0442\u044b'), ('\u0410\u0441\u0442\u0430\u043d\u0430', '\u0410\u0441\u0442\u0430\u043d\u0430'), ('\u0410\u043a\u0442\u0430\u0443', '\u0410\u043a\u0442\u0430\u0443'), ('\u0410\u043a\u0442\u043e\u0431\u0435', '\u0410\u043a\u0442\u043e\u0431\u0435'), ('\u0410\u0441\u0442\u0430\u043d\u0430', '\u0410\u0441\u0442\u0430\u043d\u0430'), ('\u0410\u0442\u044b\u0440\u0430\u0443', '\u0410\u0442\u044b\u0440\u0430\u0443'), ('\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d', '\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d'), ('\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430', '\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430'), ('\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443', '\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443'), ('\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439', '\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439'), ('\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430', '\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430'), ('\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440', '\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440'), ('\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b\u043e\u0432\u0441\u043a', '\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b\u043e\u0432\u0441\u043a'), ('\u0421\u0435\u043c\u0435\u0439', '\u0421\u0435\u043c\u0435\u0439'), ('\u0422\u0430\u043b\u0434\u044b\u043a\u043e\u0440\u0433\u0430\u043d', '\u0422\u0430\u043b\u0434\u044b\u043a\u043e\u0440\u0433\u0430\u043d'), ('\u0422\u0430\u0440\u0430\u0437', '\u0422\u0430\u0440\u0430\u0437'), ('\u0423\u0440\u0430\u043b\u044c\u0441\u043a', '\u0423\u0440\u0430\u043b\u044c\u0441\u043a'), ('\u0423\u0441\u0442\u044c-\u041a\u0430\u043c\u0435\u043d\u043e\u0433\u043e\u0440\u0441\u043a', '\u0423\u0441\u0442\u044c-\u041a\u0430\u043c\u0435\u043d\u043e\u0433\u043e\u0440\u0441\u043a'), ('\u0428\u044b\u043c\u043a\u0435\u043d\u0442', '\u0428\u044b\u043c\u043a\u0435\u043d\u0442')], max_length=200, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('district', models.CharField(max_length=200, verbose_name='\u0420\u0430\u0439\u043e\u043d')),
                ('price', models.BigIntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('storey', models.CharField(max_length=200, verbose_name='\u042d\u0442\u0430\u0436')),
                ('areaUseful', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u0435\u0437\u043d\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('constYear', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u043f\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')),
                ('wallMaterial', models.CharField(max_length=200, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b \u0441\u0442\u0435\u043d')),
                ('floor', models.CharField(max_length=200, verbose_name='\u041f\u043e\u043b\u044b')),
                ('hotwaterSupply', models.CharField(max_length=200, verbose_name='\u0413\u043e\u0440\u044f\u0447\u0435\u0435 \u0432\u043e\u0434\u043e\u0441\u043d\u0430\u0431\u0436\u0435\u043d\u0438\u0435')),
                ('waterSupply', models.CharField(max_length=200, verbose_name='\u0412\u043e\u0434\u043e\u0441\u043d\u0430\u0431\u0436\u0435\u043d\u0438\u0435')),
                ('sewerage', models.CharField(max_length=200, verbose_name='\u041a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f')),
                ('powerSupply', models.CharField(max_length=200, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u0441\u043d\u0430\u0431\u0436\u0435\u043d\u0438\u0435')),
                ('heating', models.CharField(max_length=200, verbose_name='\u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0435')),
                ('phone', models.CharField(max_length=200, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('internet', models.CharField(max_length=200, verbose_name='\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442')),
                ('safety', models.CharField(max_length=200, verbose_name='\u0411\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c')),
                ('footer', models.CharField(max_length=200, verbose_name='\u041f\u043e\u0434\u0432\u0430\u043b')),
                ('purpose', models.CharField(max_length=200, verbose_name='\u0426\u0435\u043b\u0435\u0432\u043e\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('contacts', models.TextField(verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
                ('contactFace', models.CharField(max_length=200, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('address', models.CharField(max_length=400, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 1')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 2')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 3')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 4')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 5')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f',
            },
        ),
        migrations.CreateModel(
            name='CommercialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('suggested_price', models.BigIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u043d\u0430\u044f \u0446\u0435\u043d\u0430, \u0442\u0433')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0434\u0430\u0447\u0438 \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0438\u0435',
            },
        ),
        migrations.AlterField(
            model_name='flat',
            name='storey',
            field=models.CharField(max_length=200, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
    ]
