# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papp', '0016_auto_autoorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('\u0410\u043b\u043c\u0430\u0442\u044b', '\u0410\u043b\u043c\u0430\u0442\u044b'), ('\u0410\u0441\u0442\u0430\u043d\u0430', '\u0410\u0441\u0442\u0430\u043d\u0430'), ('\u0410\u043a\u0442\u0430\u0443', '\u0410\u043a\u0442\u0430\u0443'), ('\u0410\u043a\u0442\u043e\u0431\u0435', '\u0410\u043a\u0442\u043e\u0431\u0435'), ('\u0410\u0441\u0442\u0430\u043d\u0430', '\u0410\u0441\u0442\u0430\u043d\u0430'), ('\u0410\u0442\u044b\u0440\u0430\u0443', '\u0410\u0442\u044b\u0440\u0430\u0443'), ('\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d', '\u0416\u0435\u0437\u043a\u0430\u0437\u0433\u0430\u043d'), ('\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430', '\u041a\u0430\u0440\u0430\u0433\u0430\u043d\u0434\u0430'), ('\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443', '\u041a\u043e\u043a\u0448\u0435\u0442\u0430\u0443'), ('\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439', '\u041a\u043e\u0441\u0442\u0430\u043d\u0430\u0439'), ('\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430', '\u041a\u044b\u0437\u044b\u043b\u043e\u0440\u0434\u0430'), ('\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440', '\u041f\u0430\u0432\u043b\u043e\u0434\u0430\u0440'), ('\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b\u043e\u0432\u0441\u043a', '\u041f\u0435\u0442\u0440\u043e\u043f\u0430\u0432\u043b\u043e\u0432\u0441\u043a'), ('\u0421\u0435\u043c\u0435\u0439', '\u0421\u0435\u043c\u0435\u0439'), ('\u0422\u0430\u043b\u0434\u044b\u043a\u043e\u0440\u0433\u0430\u043d', '\u0422\u0430\u043b\u0434\u044b\u043a\u043e\u0440\u0433\u0430\u043d'), ('\u0422\u0430\u0440\u0430\u0437', '\u0422\u0430\u0440\u0430\u0437'), ('\u0423\u0440\u0430\u043b\u044c\u0441\u043a', '\u0423\u0440\u0430\u043b\u044c\u0441\u043a'), ('\u0423\u0441\u0442\u044c-\u041a\u0430\u043c\u0435\u043d\u043e\u0433\u043e\u0440\u0441\u043a', '\u0423\u0441\u0442\u044c-\u041a\u0430\u043c\u0435\u043d\u043e\u0433\u043e\u0440\u0441\u043a'), ('\u0428\u044b\u043c\u043a\u0435\u043d\u0442', '\u0428\u044b\u043c\u043a\u0435\u043d\u0442')], max_length=200, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('color', models.CharField(choices=[('\u0431\u0440\u043e\u043d\u0437\u0430', '\u0431\u0440\u043e\u043d\u0437\u0430'), ('\u0432\u0438\u0448\u043d\u044f', '\u0432\u0438\u0448\u043d\u044f'), ('\u0445\u0430\u043c\u0435\u043b\u0435\u043e\u043d', '\u0445\u0430\u043c\u0435\u043b\u0435\u043e\u043d'), ('\u0431\u0435\u0436\u0435\u0432\u044b\u0439', '\u0431\u0435\u0436\u0435\u0432\u044b\u0439'), ('\u0431\u0435\u043b\u044b\u0439', '\u0431\u0435\u043b\u044b\u0439'), ('\u0431\u0438\u0440\u044e\u0437\u043e\u0432\u044b\u0439', '\u0431\u0438\u0440\u044e\u0437\u043e\u0432\u044b\u0439'), ('\u0431\u043e\u0440\u0434\u043e\u0432\u044b\u0439', '\u0431\u043e\u0440\u0434\u043e\u0432\u044b\u0439'), ('\u0433\u043e\u043b\u0443\u0431\u043e\u0439', '\u0433\u043e\u043b\u0443\u0431\u043e\u0439'), ('\u0436\u0451\u043b\u0442\u044b\u0439', '\u0436\u0451\u043b\u0442\u044b\u0439'), ('\u0437\u0435\u043b\u0451\u043d\u044b\u0439', '\u0437\u0435\u043b\u0451\u043d\u044b\u0439'), ('\u0437\u043e\u043b\u043e\u0442\u0438\u0441\u0442\u044b\u0439', '\u0437\u043e\u043b\u043e\u0442\u0438\u0441\u0442\u044b\u0439'), ('\u043a\u043e\u0440\u0438\u0447\u043d\u0435\u0432\u044b\u0439', '\u043a\u043e\u0440\u0438\u0447\u043d\u0435\u0432\u044b\u0439'), ('\u043a\u0440\u0430\u0441\u043d\u044b\u0439', '\u043a\u0440\u0430\u0441\u043d\u044b\u0439'), ('\u043e\u0440\u0430\u043d\u0436\u0435\u0432\u044b\u0439', '\u043e\u0440\u0430\u043d\u0436\u0435\u0432\u044b\u0439'), ('\u0440\u043e\u0437\u043e\u0432\u044b\u0439', '\u0440\u043e\u0437\u043e\u0432\u044b\u0439'), ('\u0441\u0435\u0440\u0435\u0431\u0440\u0438\u0441\u0442\u044b\u0439', '\u0441\u0435\u0440\u0435\u0431\u0440\u0438\u0441\u0442\u044b\u0439'), ('\u0441\u0435\u0440\u044b\u0439', '\u0441\u0435\u0440\u044b\u0439'), ('\u0441\u0438\u043d\u0438\u0439', '\u0441\u0438\u043d\u0438\u0439'), ('\u0441\u0438\u0440\u0435\u043d\u0435\u0432\u044b\u0439', '\u0441\u0438\u0440\u0435\u043d\u0435\u0432\u044b\u0439'), ('\u0444\u0438\u043e\u043b\u0435\u0442\u043e\u0432\u044b\u0439', '\u0444\u0438\u043e\u043b\u0435\u0442\u043e\u0432\u044b\u0439'), ('\u0447\u0451\u0440\u043d\u044b\u0439', '\u0447\u0451\u0440\u043d\u044b\u0439')], max_length=200, verbose_name='\u0426\u0432\u0435\u0442')),
                ('price', models.BigIntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('manufYear', models.IntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430')),
                ('brand', models.CharField(max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430')),
                ('equipmentType', models.CharField(max_length=200, verbose_name='\u0422\u0438\u043f \u0442\u0435\u0445\u043d\u0438\u043a\u0438')),
                ('fuelType', models.CharField(max_length=200, verbose_name='\u0422\u0438\u043f \u0442\u043e\u043f\u043b\u0438\u0432\u0430')),
                ('contacts', models.TextField(verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
                ('contactFace', models.CharField(max_length=200, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 1')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 2')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 3')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 4')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e 5')),
            ],
            options={
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0442\u0435\u0445\u043d\u0438\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='EquipmentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('suggested_price', models.BigIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u043d\u0430\u044f \u0446\u0435\u043d\u0430, \u0442\u0433')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0434\u0430\u0447\u0438 \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0441\u043f\u0435\u0446\u0442\u0435\u0445\u043d\u0438\u043a\u0443',
            },
        ),
    ]
